### ISSUE TITLE
Running App indicator

### ISSUE THREAD

**Issue by deshant** [RobinJ1995/DistroHopper#6]
bug: indicator is not updated when an app is no longer running.
my device : Xperia Go (MDPI device, rooted, modified framework)
ROM : JB 4.1.2
Note : In Xperia devices, an app is closed when you swipe it from the recent apps / task switcher pane.
The running app indicator in launcher is not getting updated. Same is seen while using in-app launcher (Experimental feature).
The launcher however gets updated after visiting its preferences, or launching another app, or even when screen is locked and unlocked again.

**Comment by Maik1999** [comment]
The App Indicator doesn't works on the Oneplus One with Android 5.0.1 SlimSaber. It doesn't show any running app.

**Comment by RobinJ1995** [comment]
It doesn't work on *any* device running Android 5.0 or higher since Google seems to have wrecked the API that I was using :) If I decide to keep this feature for the next release I'll need to rewrite it anyway since it never really worked properly.

**Comment by Maik1999** [comment]
Oh. Thats not nice.
Hope you get it work anyway.

**Comment by RobinJ1995** [comment]
@Maik1999 Well it's kinda working now on Android 5.x... It just shows *way* too many running apps since there no longer seems to be any way to check whether the app is supposed to be a foreground app (as in an app like Facebook or GMail, which the user manually launched) or a service that just needs to do work in background.

These are all services that are running in background;
![screenshot_2015-07-25-19-37-35](https://cloud.githubusercontent.com/assets/3089559/8890550/7351b930-3305-11e5-8ee5-077d5ac4ea0c.png)

So I can leave the option there, but either way I'll probably have to add a big warning label saying it's pretty much useless on Android 5.x :unamused:

**Comment by RobinJ1995** [comment]
This feature has been removed (or at least hidden). Closing this as I'm not sure I care enough to re-implement it.
